name: Build static blog

on:
  push:
    paths:
      - issues/*
      - public/*
      - templates/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  issue-to-html-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build static files
        id: issue-to-html
        run: node dist/index.js

      # TODO publish to gh pages
      # remove these other steps

      - name: Check diff
        id: check-diff
        run: |
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Diff has changes to commit"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "::warning title=Nothing to commit::Not rebuilding or deploying."
          fi

      - name: Commit and push
        if: ${{ steps.check-diff.outputs.changed == 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "${{ steps.issue-to-html.outputs.commit-message }}"
          git push
