name: Sync Issue With Files

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

jobs:
  sync-issue-with-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dump issue to JSON
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          # https://docs.github.com/en/rest/issues/issues#get-an-issue
          script: |
            const context_issue = JSON.stringify(context.issue);
            const context_payload = JSON.stringify(context.payload.issue.body);
            console.log(context_issue)
            console.log(context_payload)
            const fs = require('fs');
            fs.writeFileSync(`./issue_${issue_number}.txt`, issue_body);

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Issue to Post"
          git add .
          git commit -m "Add issue body to file"
          git push
