name: Sync issues
# run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
# https://github.com/actions/github-script?tab=readme-ov-file#result-encoding
jobs:
  sync-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: posts

      - name: Dump issue to JSON
        id: dump-issue-json
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const path = `post/${context.issue.number}.json`;
            const fs = require('fs');
            fs.writeFileSync(path, JSON.stringify(context.payload.issue));
            console.log('context', JSON.stringify(context));
            const output =  {
              'commit-msg': `Issue sync: ${context.payload.action} issue #${context.issue.number}${context.payload.changes ? ' ' + Object.keys(context.payload.changes).join(', ') : ''}`
            };
            console.log('output', JSON.stringify(output));
            return output;

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Issue to Post"
          git add .
          echo "commit-msg ${{ steps.dump-issue-json.outputs.commit-msg }}"
          echo "result ${{ steps.dump-issue-json.outputs.result }}"
          git commit -m "${{ steps.dump-issue-json.outputs.commit-msg }}"
          git push
