name: Issue to HTML

on:
  push:
    paths:
      - issues/*
  workflow_dispatch:

jobs:
  issue-to-html-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run node
        id: issue-to-html
        run: node dist/index.js

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "${{ steps.issue-to-html.outputs.commit-message }}"
          git push
