name: Sync Issue With Files

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

jobs:
  sync-issue-with-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dump issue to JSON
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          # https://docs.github.com/en/rest/issues/issues#get-an-issue
          script: |
            const fs = require('fs');
            fs.mkdirSync(`./post/${context.issue.number}.json`, { recursive: true });
            fs.writeFileSync(`./post/${context.issue.number}.json`, JSON.stringify(context.payload.issue));
            console.log(JSON.stringify(context));
            process.env.ISSUE_NUMBER = context.issue.number;

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Issue to Post"
          git add .
          git commit -m "Add issue $ISSUE_NUMBER body to file"
          git push
