name: Sync issues

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

run-name: "Sync issues"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  sync-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # TODO filter out stuff from the blacklist/whitelist
      # delete issues not made by the opener?

      - name: Save issue to JSON
        id: issue-to-json
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const path = `issues/`;
            const fs = require('fs');
            if (!fs.existsSync()) fs.mkdirSync(path, { recursive: true });
            fs.writeFileSync(`${path}${context.issue.number}.json`, JSON.stringify(context.payload.issue, null, 2));

            const changesSummary = context.payload.changes ? ' ' + Object.keys(context.payload.changes).reduce((a, c, i, arr) => { if (i === 0) return c; if (i === arr.length - 1) return `${a} & ${c}`; return `${a}, ${c}`;}, '') : '';
            return `Issue sync: ${context.payload.action} issue #${context.issue.number}${changesSummary}`;
          result-encoding: string

      - name: Check diff
        id: check-diff
        run: |
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Diff has changes to commit"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "::warning title=Nothing to commit::Not rebuilding or deploying."
          fi

      - name: Commit and push
        if: ${{ steps.check-diff.outputs.changed == 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "${{ steps.issue-to-json.outputs.result }}"
          git pull --rebase
          git push

      - name: Build static site
        if: ${{ steps.check-diff.outputs.changed == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run build-static.yml
