name: Sync issues

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

run-name: "Sync issue: ${{ github.event.action }} #${{ github.event.issue.number }}"

jobs:
  sync-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: issues

      - name: Dump issue to JSON
        id: dump-issue
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const path = `${context.issue.number}.json`;
            const fs = require('fs');
            fs.writeFileSync(path, JSON.stringify(context.payload.issue));
            // console.log('context', JSON.stringify(context));
            return `Issue sync: ${context.payload.action} issue #${context.issue.number}${context.payload.changes ? ' ' + Object.keys(context.payload.changes).join(', ') : ''}`;
          result-encoding: string

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Issue to Post"
          git add .
          git commit -m "${{ steps.dump-issue.outputs.result }}"
          git push
