name: Sync issues

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

run-name: "Sync issue #${{ github.event.issue.number }}"

jobs:
  sync-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dump issue to JSON
        id: dump-issue
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const path = `issues/`;
            const fs = require('fs');
            if (!fs.existsSync()) fs.mkdirSync(path, { recursive: true });
            fs.writeFileSync(`${path}${context.issue.number}.json`, JSON.stringify(context.payload.issue));
            const formattedChanges = context.payload.changes ? ' ' + Object.keys(context.payload.changes).reduce((a, c, i, arr) => { if (i === 0) return c; if (i === arr.length - 1) return `${a} & ${c}`; return `${a}, ${c}`;}, '') : '';
            return `Issue sync: ${context.payload.action} issue #${context.issue.number}${formattedChanges}`;
          result-encoding: string

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Issue to Post"
          git add .
          git commit -m "${{ steps.dump-issue.outputs.result }}"
          git push
